stages:
  - lint
  - test

lint:
  stage: lint
  tags:
    - docker
  image: tensorflow/tensorflow:latest
  script:
    - export PATH="$PATH:/root/.local/bin"
    - pip install flake8 --user
    - flake8 lbn.py test.py setup.py

unittest_tf1_py2:
  stage: test
  tags:
    - docker
  image: tensorflow/tensorflow:1.13.1
  script:
    - python -m unittest test

unittests_tf1_py3:
  stage: test
  tags:
    - docker
  image: tensorflow/tensorflow:1.13.1-py3
  script:
    - python -m unittest test

unittest_tf2_py2:
  stage: test
  tags:
    - docker
  image: tensorflow/tensorflow:2.0.0a0
  script:
    - python -m unittest test

unittests_tf2_py3:
  stage: test
  tags:
    - docker
  image: tensorflow/tensorflow:2.0.0a0-py3
  script:
    - python -m unittest test
